services:
  ganaderiagateway:
    image: herbertcode/ganaderiagateway
    #deploy:
     # resources:
      #  limits:
       #   memory: 300M
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms128m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_R2DBC_URL=r2dbc:postgresql://ganaderiagateway-postgresql:5432/ganaderiaGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://ganaderiagateway-postgresql:5432/ganaderiaGateway
      - SPRING_ELASTICSEARCH_URIS=http://ganaderiagateway-elasticsearch:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092    
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      ganaderiagateway-postgresql:
        condition: service_healthy
      ganaderiagateway-elasticsearch:
        condition: service_healthy
  ganaderiagateway-postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=ganaderiaGateway
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5435:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10
  ganaderiagateway-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3 #docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          memory: 350M  
    ports:
      - 9200:9200
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s #- http://localhost:9200/_cluster/health?wait_for_status=green&timeout=30s
      interval: 5s
      timeout: 30s
      retries: 15

  ganaderiaafiliadosservice:
    image: herbertcode/ganaderiaafiliadosservice
    #deploy:
     # resources:
      #  limits:
       #   cpus: '1'       # Límite de CPU
        #  memory: 1G
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms128m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ganaderiaafiliadosservice-postgresql:5432/ganaderiaAfiliadosService
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://ganaderiaafiliadosservice-postgresql:5432/ganaderiaAfiliadosService
      #- SPRING_ELASTICSEARCH_URIS=http://ganaderiaafiliadosservice-elasticsearch:9201
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    ports:
      - 8081:8081
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      ganaderiaafiliadosservice-postgresql:
        condition: service_healthy
      #ganaderiaafiliadosservice-elasticsearch:
       # condition: service_healthy
  ganaderiaafiliadosservice-postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=ganaderiaAfiliadosService
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5436:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10
  #ganaderiaafiliadosservice-elasticsearch:
   # image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    #environment:
     # - ES_JAVA_OPTS=-Xms512m -Xmx512m
      #- discovery.type=single-node
      #- xpack.security.enabled=false
    #healthcheck:
     # test:
      #  - CMD
       # - curl
       # - -f
       # - http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s #- http://localhost:9200/_cluster/health?wait_for_status=green&timeout=10s
      #interval: 5s
      #timeout: 30s #10s
      #retries: 15 #10
    #ports:
    #- 9201:9200

  consul:
    image: docker.io/bitnami/consul:1.21.0
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
  consul-config-loader:
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
